inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

  TargetRubyVersion: 3.1

Style/Documentation:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Max: 25
    

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'
    - 'db/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
