default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: supersecretpass

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_api_development

test:
  <<: *default
  database: blog_api_test

production:
  <<: *default
  database: blog_api_production
